# https://docs.travis-ci.com/user/deployment/pages/
language: ruby
dist: xenial
os:
  - linux
rvm: 2.3.0
# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  - sudo apt-get -y install graphviz
script: bundle exec rake deploy
