language: ruby
dist: xenial
os:
  - linux
rvm: 2.3.0
# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  - sudo apt-get -y install graphviz
script: bundle exec rake deploy
env:
  global:
    secure: SYcwtTyVK9+cdxFD+H6QK5iSVZr5G+PrmP0U5fveQ6Y7zB0j29MzMcb8mptQDffKAVEOPfTLSXPCzW7PVs0y/QzLpwGm8vgjoBQOP3Wq9+52TBKJFI5NqVZic+U54NzrBStDg+pOkxvDvaTFjUJtCIhb3fmGYpTJzsJJItKKGBjAOg4El/dhHpTA8Y087GKyjTKU7MfisnWhdd+Y08ZDDFqrfpCdVGeTUbQRxR2ASsRDrkzedLC7Cq7WT42zBW+Y1k/WkCtQyp1ZktpRUM6mCZpcyRGoO2qYgptJjX1FYDBqyusImZ/DD+MbmtZ4ik58C4DRtuCpkszgkDQxMOLTH+XOpmKYHxbD8bimrR6NaK7QgyLiKm7xtgChcq+lEZSZQ29M5mQhsuFg+s1ZV+BoEUroKXykLhz13tEvhvJalSeamK/UXX11ntSdofzzmWuasgaSBC3GmGBaW8m3nOysAtyf6SZK1e5doKNi23RKeF0MrufGiLpa4ZP6k9lSj7C3DmatxklAX7DrKzBJkE6CH/IFyiUqoiizpxyln2fQNrUGcOmRAP7HkoHtBX4AAGAEYS1zAvQkU/OWgCromKjBxUt2SddZ2ir6Vlk4002f9SD0KfjwwaaeA2qK6SiqYDpFZttc3ynOyWEg42r1sYMT/oQCOYVufUhLF5Mb+Wim59w=
